Object-Oriented Programming(Continution....):

Python Packages and modules using oop's:

In [ ]:
- sample.py ----> classes

In [ ]:
# modules:
- we will call.py files as a module(.py)
- module is a group of functions and classes.

In [ ]:
# packages:
- it is a folder
- collection of modules is called as packages(Folder)

In [4]:
# module2.py from packages
from packages.module2 import Calsi
obj = Calsi
print(obj.add(4,5))
print(obj.sub(4,5))
print(obj.mul(4,5))
print(obj.div(4,5))
print(obj.mod(4,5))

9
-1
20
0.8
4


In [4]:
from packages.module2 import *
obj1 = Math
print(obj1.power(2,3))
print(obj1.power(2,4))
print(obj1.isEven(5))
print(obj1.isEven(6))

obj2 = Calsi
print(obj2.add(26,8))
print(obj2.sub(43,5))

8
16
Odd
Even
34
38


In [4]:
from packages.module2 import *
obj2 = Calsi1(2,5) # because we are using constructor that's why we are taking ().
print(obj2.__add__())
print(obj2.__mul__())

7
10


In [5]:
# destructor
class table:
    def __init__(self):
        print("table created")
    def __del__(self):
        print("destructor called,table deleted")
obj = table()
del obj

table created
destructor called,table deleted


In [ ]:
# Data Science:
- for organizing, processing,analysing the huge amount of data.
- datavisualization
- extracting the data from source
### nearly 20 python libraries for datascience
# 3:
- numpy
- pandas
- matplotlib

# numpy(numerical python):
- it is a fundamental package for scientific computing in python
- numpy is a python library
- it is used to create multi dimensional arrays for fast operarions.
- # for install numpy:
    - pip install numpy
- # fro using numpy:
    - import numpy as np

In [6]:
# 1 dimensional array:
import numpy as np
array1d = np.array([1,2,3,4,5])
print(array1d)
print(type(array1d))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# 2 dimensional array:
import numpy as np
array2d = np.array([[2,3,4,5],[4,5,6,7]])
print(array2d)
print(type(array2d))

[[2 3 4 5]
 [4 5 6 7]]
<class 'numpy.ndarray'>


In [9]:
# 2 dimensional array:
import numpy as np
array2d = np.array([[2,3,4,5],[4,5,6]])
print(array2d)
print(type(array2d))
array2d

[list([2, 3, 4, 5]) list([4, 5, 6])]
<class 'numpy.ndarray'>


array([list([2, 3, 4, 5]), list([4, 5, 6])], dtype=object)

In [11]:
# 1 dimensional array(differen data types):
import numpy as np
arrayd = np.array([23,45,'python',89.04])
print(arrayd)
print(type(arrayd))
arrayd

['23' '45' 'python' '89.04']
<class 'numpy.ndarray'>


array(['23', '45', 'python', '89.04'], dtype='<U11')

In [14]:
import numpy as np
print(dir(np),end=' ')

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [17]:
import numpy as np
a = np.arange(10)
print(a)
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
a=np.arange(15).reshape(3,7)
print(a)
print(type(a))

ValueError: cannot reshape array of size 15 into shape (3,7)

In [4]:
import numpy as np
a=np.arange(1,16,2)
print(a)
print(type(a))

[ 1  3  5  7  9 11 13 15]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
a=np.arange(10000)
print(a)
print(type(a))

[   0    1    2 ... 9997 9998 9999]
<class 'numpy.ndarray'>


In [22]:
import numpy as np
a = np.arange(10000).reshape(100,100)
print(a)
print(type(a))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
<class 'numpy.ndarray'>


In [23]:
import numpy as np
np.__version__

'1.18.5'

In [24]:
np.array([1,3,4,5,6,67],dtype="float")

array([ 1.,  3.,  4.,  5.,  6., 67.])

In [26]:
a = np.array([1,3,4,5.89,6,67])
a

array([ 1.  ,  3.  ,  4.  ,  5.89,  6.  , 67.  ])

In [27]:
np.array([1,3,4,5,6.89,67.876],dtype="int")

array([ 1,  3,  4,  5,  6, 67])

In [6]:
np.array([1.89,3.8,4,5.89,6.89,67.876],dtype="str")

array(['1.89', '3.8', '4', '5.89', '6.89', '67.876'], dtype='<U6')

In [7]:
a=np.array([1.89,3.8,4,5.89,6,"67.876"])
a

array(['1.89', '3.8', '4', '5.89', '6', '67.876'], dtype='<U32')

In [8]:
np.array([range(i,i+3) for i in [2,4,6]])
# range(2,5)----> 2,3,4
# range(4,7)----> 4,5,6
# range(6,9)----> 6,7,8

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.ones((3,5),dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.full((3,5),56.89)

array([[56.89, 56.89, 56.89, 56.89, 56.89],
       [56.89, 56.89, 56.89, 56.89, 56.89],
       [56.89, 56.89, 56.89, 56.89, 56.89]])

In [14]:
np.linspace(1,10) #default 50 elements

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [15]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [16]:
np.linspace(1,10,20,retstep=True)

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [17]:
import numpy as np
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [18]:
import random
random.randint(000000,999999)

718276

In [19]:
np.random.randint(1,50,size=(4,4))

array([[20, 39, 10, 49],
       [ 6,  1, 28, 47],
       [14, 11, 15, 42],
       [42, 11, 26, 48]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [22]:
d=np.array([2,3,4,5])
np.diag(d)

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [23]:
d=np.array([2,3,4,5]*3)
d

array([2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5])

In [24]:
d=np.repeat([2,3,4,5],3)
d

array([2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [25]:
d1=np.array([2,3,4,5])
d2=np.array([3,4,5,6])
d1+d2

array([ 5,  7,  9, 11])

In [26]:
d1*3

array([ 6,  9, 12, 15])

In [27]:
#nd arrays:
a=np.array([[1,2,3],[2,3,4]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize) #it returns size in bytes

[[1 2 3]
 [2 3 4]]
2
(2, 3)
6
int32
4


In [28]:
a[::-1]

array([[2, 3, 4],
       [1, 2, 3]])

In [29]:
d1=np.arange(1,5).reshape(2,2)
d2=np.arange(5,9).reshape(2,2)
print(d1)
print(d2)
print(d1+d2)
print(d1-d2)
print(d1*d2)
print(d1/d2)
print(d1%d2)
print(d1.dot(d2)) #matrix multiplication

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1 2]
 [3 4]]
[[19 22]
 [43 50]]


In [30]:
x=np.array([2,4,6,1,8])
np.sort(x)

array([1, 2, 4, 6, 8])

In [31]:
a=np.array([[1,2,3],[2,3,4]])
print(a)
print(a.min())
print(a.max())
print(a.sum())

[[1 2 3]
 [2 3 4]]
1
4
15


In [32]:
a=np.array([[1,2,3],[2,3,4]])
print(a)
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.log(a))

[[1 2 3]
 [2 3 4]]
[[1.         1.41421356 1.73205081]
 [1.41421356 1.73205081 2.        ]]
[[ 0.84147098  0.90929743  0.14112001]
 [ 0.90929743  0.14112001 -0.7568025 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.41614684 -0.9899925  -0.65364362]]
[[0.         0.69314718 1.09861229]
 [0.69314718 1.09861229 1.38629436]]


In [33]:
a=np.array([[1,2,3],[2,3,4]])
print(a)
print(a.max(axis=0)) #axis=0 means rows max
print(a.max(axis=1)) #axis=1 means columns max

[[1 2 3]
 [2 3 4]]
[2 3 4]
[3 4]


In [34]:
a=np.arange(3)
print(a)
print(a[0])
print(a[2])
print(a<1)

[0 1 2]
0
2
[ True False False]


In [35]:
a=np.arange(3)
print(a)
b=np.arange(4)[:,np.newaxis]
print(b)

[0 1 2]
[[0]
 [1]
 [2]
 [3]]


In [ ]:
# task1:
in numpy methods:
 #vstack
 #hstack

In [2]:
#  hstack _ _ horizontally(column wise)
import numpy as np
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [5]:
# vstack
import numpy as np
c = np.array(([1],[2],[3]))
d = np.array(([4],[5],[6]))
np.vstack((c,d))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])